name: Firebase Hosting Deploy

on:
  push:
    branches: 
      - release/*

jobs:
  build:
    
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}
    - name: Check Branch
      run: echo ${{ github.ref }}
